2023-06-02 23:04:07,868 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-06-02 23:04:14,679 INFO server.py Установлено соедение с ПК ('127.0.0.1', 63173)
2023-06-02 23:04:14,679 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1685729054.6792338, 'user': {'account_name': 'Guest'}}
2023-06-02 23:04:14,679 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1685729054.6792338, 'user': {'account_name': 'Guest'}}
2023-06-02 23:04:14,679 INFO server.py Cформирован ответ клиенту {'response': 200}
2023-06-02 23:04:14,679 DEBUG server.py Соединение с клиентом ('127.0.0.1', 63173) закрывается.
2023-06-02 23:04:50,949 CRITICAL config_server_log.py Критическая ошибка
2023-06-02 23:04:50,950 ERROR config_server_log.py Ошибка
2023-06-02 23:04:50,950 DEBUG config_server_log.py Отладочная информация
2023-06-02 23:04:50,950 INFO config_server_log.py Информационное сообщение
2023-06-02 23:06:50,072 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-06-02 23:06:54,532 INFO server.py Установлено соедение с ПК ('127.0.0.1', 63182)
2023-06-02 23:06:54,532 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1685729214.5329092, 'user': {'account_name': 'Guest'}}
2023-06-02 23:06:54,533 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1685729214.5329092, 'user': {'account_name': 'Guest'}}
2023-06-02 23:06:54,533 INFO server.py Cформирован ответ клиенту {'response': 200}
2023-06-02 23:06:54,533 DEBUG server.py Соединение с клиентом ('127.0.0.1', 63182) закрывается.
2023-06-02 23:07:01,596 CRITICAL config_server_log.py Критическая ошибка
2023-06-02 23:07:01,596 ERROR config_server_log.py Ошибка
2023-06-02 23:07:01,596 DEBUG config_server_log.py Отладочная информация
2023-06-02 23:07:01,596 INFO config_server_log.py Информационное сообщение
2023-06-02 23:16:41,463 INFO server.py Установлено соедение с ПК ('127.0.0.1', 63275)
2023-06-02 23:16:41,463 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1685729801.4634075, 'user': {'account_name': 'Guest'}}
2023-06-02 23:16:41,463 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1685729801.4634075, 'user': {'account_name': 'Guest'}}
2023-06-02 23:16:41,463 INFO server.py Cформирован ответ клиенту {'response': 200}
2023-06-02 23:16:41,463 DEBUG server.py Соединение с клиентом ('127.0.0.1', 63275) закрывается.
2023-06-02 23:25:50,692 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-06-02 23:26:01,697 INFO server.py Установлено соедение с ПК ('127.0.0.1', 37700)
2023-06-02 23:26:01,697 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1685730361.697255, 'user': {'account_name': 'Guest'}}
2023-06-02 23:26:01,697 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1685730361.697255, 'user': {'account_name': 'Guest'}}
2023-06-02 23:26:01,697 INFO server.py Cформирован ответ клиенту {'response': 200}
2023-06-02 23:26:01,697 DEBUG server.py Соединение с клиентом ('127.0.0.1', 37700) закрывается.
2023-06-02 23:26:08,327 CRITICAL config_server_log.py Критическая ошибка
2023-06-02 23:26:08,327 ERROR config_server_log.py Ошибка
2023-06-02 23:26:08,327 DEBUG config_server_log.py Отладочная информация
2023-06-02 23:26:08,327 INFO config_server_log.py Информационное сообщение
